## YAML Template.
---
name: Monsters vs Players
version: BETA 1.0
main: org.cat.main

commands:
    start:
        description: Starts the game
        usage: /start

    end:
        description: Ends the game
        usage: /end